markup:
  # Markup
  # We assume we're using Goldmark
  # https://gohugo.io/getting-started/configuration-markup#readout
  # ################################
  highlight:
    style: monokai
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
    parser:
      attribute:
        block: true
        title: true
module:
  hugoVersion:
    extended: true
    # Bumping minVersion? Search comments for +minVer+ first.
    min: "0.120.0"
  mounts:
  - source: assets
    target: assets
  - source: layouts
    target: layouts
  - source: core
    target: layouts/partials/huge

  imports:
  - path: github.com/theNewDynamic/hugo-module-tnd-seo
  - path: github.com/theNewDynamic/hugo-module-tnd-media